#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

LRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'

BRANCH_REGEXP='EC-[0-9]+'
FILES_PATTERN='\.(ts)(\..+)?$'
FORBIDDEN='console\.[clear|dir|log|info|warn|error]'


run_linter () {
  echo -e "${PURPLE}Linting the src folder ==> ${NC}${CYAN}Ext: .js, .ts, .scss${NC}"
  npx lint-staged
  if [[ $? -ne 0 ]]
  then
    exit 1
  fi
}

run_linter

printf "${GREEN}Proceeding with commit...${NC}\n"